server {
    listen 80;
    server_name ; # Заменишь на IP из Timeweb

    location = /favicon.ico { access_log off; log_not_found off; }

    # Отдача статики (стили, картинки админки)
    location /static/ {
        alias /root/smartmeal-android/server/staticfiles/;
    }

    # Отдача загруженных пользователями фото
    location /media/ {
        alias /root/smartmeal-android/server/media/;
    }

    # Все остальные запросы шлем в Django через Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/root/smartmeal-android/server/smartmeal.sock;
    }
    }}
