server {
    listen 80;
    listen [::]:80; # Включаем поддержку IPv6
    
    server_name [2a03:6f00:a::1:d3c2]; # Твой IPv6 адрес в скобках

    location = /favicon.ico { access_log off; log_not_found off; }

    # Раздача статики
    location /static/ {
        alias /root/smartmeal-android/server/staticfiles/;
    }

    # Раздача медиа
    location /media/ {
        alias /root/smartmeal-android/server/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/root/smartmeal-android/server/smartmeal.sock;
    }
    }}