# Generated by Django 6.0.3 on 2026-03-07 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('recipes', '0002_alter_ingredient_category_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diettype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portion_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('recipe',), ('user',)},
        ),
        migrations.AlterModelTable(
            name='allergy',
            table='allergy',
        ),
        migrations.AlterModelTable(
            name='diettype',
            table='diet_type',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userfavorite',
            table='user_favorite',
        ),
    ]
