# Generated by Django 6.0.3 on 2026-03-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_password'),
        ('recipes', '0003_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'recipe')},
        ),
    ]
