# Generated by Django 6.0.3 on 2026-03-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userfavorite_unique_together'),
        ('recipes', '0003_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='diettype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='diet_types',
        ),
        migrations.AddField(
            model_name='user',
            name='diet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.diettype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'created_at'], name='user_favori_user_id_0b5b8f_idx'),
        ),
    ]
