# Generated by Django 6.0.3 on 2026-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfavorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['name'], 'verbose_name': 'Аллергия', 'verbose_name_plural': 'Аллергии'},
        ),
        migrations.AlterModelOptions(
            name='diettype',
            options={'ordering': ['name'], 'verbose_name': 'Тип питания', 'verbose_name_plural': 'Типы питания'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранный рецепт пользователя', 'verbose_name_plural': 'Избранные рецепты пользователей'},
        ),
    ]
