# Generated by Django 6.0.3 on 2026-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_allergy_options_alter_diettype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_cook_time',
            field=models.CharField(choices=[('short', 'До 30 минут'), ('medium', 'От 30 до 60 минут'), ('long', 'Более часа'), ('any', 'Любое время')], default='any', max_length=10, verbose_name='Предпочитаемое время готовки'),
        ),
    ]
