# Generated by Django 6.0.3 on 2026-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_preferred_cook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_cook_time',
            field=models.CharField(choices=[('short', 'До 30 минут'), ('medium', 'От 30 до 60 минут'), ('long', '60 минут и более'), ('any', 'Любое время')], default='any', max_length=10, verbose_name='Предпочитаемое время готовки'),
        ),
    ]
