# Generated by Django 6.0.3 on 2026-04-03 13:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_preferred_cook_time'),
        ('recipes', '0018_remove_unitconversion_unique_ingredient_unit_conversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_users_stock', to='recipes.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ингредиент в наличии у пользователя',
                'verbose_name_plural': 'Ингредиенты в наличии у пользователей',
                'db_table': 'user_stock',
                'ordering': ['user', 'ingredient', 'amount'],
                'constraints': [models.UniqueConstraint(fields=('user', 'ingredient'), name='unique_user_ingredient_in_stock')],
            },
        ),
    ]
