# Generated by Django 6.0.3 on 2026-04-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['-id'], 'verbose_name': 'Аллергия', 'verbose_name_plural': 'Аллергии'},
        ),
        migrations.AlterModelOptions(
            name='diettype',
            options={'ordering': ['-id'], 'verbose_name': 'Тип питания', 'verbose_name_plural': 'Типы питания'},
        ),
    ]
