# Generated by Django 6.0.3 on 2026-04-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_avatar'),
        ('menus', '0015_alter_mealtype_options'),
        ('recipes', '0022_populate_recipe_nutrition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfavorite',
            name='unique_user_favorite_recipe',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_as', to='menus.mealtype'),
        ),
        migrations.AddConstraint(
            model_name='userfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe', 'meal_type'), name='unique_user_recipe_meal_favorite'),
        ),
    ]
