--
-- PostgreSQL database dump
--
-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-03-10 20:10:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 230 (class 1259 OID 28258)
-- Name: allergy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.allergy (
    id bigint CONSTRAINT accounts_allergy_id_not_null NOT NULL,
    name character varying(255) CONSTRAINT accounts_allergy_name_not_null NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 28257)
-- Name: accounts_allergy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.allergy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_allergy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 28266)
-- Name: diet_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diet_type (
    id bigint CONSTRAINT accounts_diettype_id_not_null NOT NULL,
    name character varying(255) CONSTRAINT accounts_diettype_name_not_null NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 28265)
-- Name: accounts_diettype_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diet_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_diettype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 28322)
-- Name: user_allergies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_allergies (
    id bigint CONSTRAINT accounts_user_allergies_id_not_null NOT NULL,
    user_id bigint CONSTRAINT accounts_user_allergies_user_id_not_null NOT NULL,
    allergy_id bigint CONSTRAINT accounts_user_allergies_allergy_id_not_null NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 28321)
-- Name: accounts_user_allergies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_allergies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_allergies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 28304)
-- Name: user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_groups (
    id bigint CONSTRAINT accounts_user_groups_id_not_null NOT NULL,
    user_id bigint CONSTRAINT accounts_user_groups_user_id_not_null NOT NULL,
    group_id integer CONSTRAINT accounts_user_groups_group_id_not_null NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 28303)
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 28282)
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint CONSTRAINT accounts_user_id_not_null NOT NULL,
    password character varying(128) CONSTRAINT accounts_user_password_not_null NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean CONSTRAINT accounts_user_is_superuser_not_null NOT NULL,
    username character varying(150) CONSTRAINT accounts_user_username_not_null NOT NULL,
    first_name character varying(150) CONSTRAINT accounts_user_first_name_not_null NOT NULL,
    last_name character varying(150) CONSTRAINT accounts_user_last_name_not_null NOT NULL,
    is_staff boolean CONSTRAINT accounts_user_is_staff_not_null NOT NULL,
    is_active boolean CONSTRAINT accounts_user_is_active_not_null NOT NULL,
    date_joined timestamp with time zone CONSTRAINT accounts_user_date_joined_not_null NOT NULL,
    email character varying(255) CONSTRAINT accounts_user_email_not_null NOT NULL,
    portion_size integer CONSTRAINT accounts_user_portion_size_not_null NOT NULL,
    created_at timestamp with time zone CONSTRAINT accounts_user_created_at_not_null NOT NULL,
    diet_type_id bigint
);


--
-- TOC entry 235 (class 1259 OID 28281)
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 28313)
-- Name: user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_user_permissions (
    id bigint CONSTRAINT accounts_user_user_permissions_id_not_null NOT NULL,
    user_id bigint CONSTRAINT accounts_user_user_permissions_user_id_not_null NOT NULL,
    permission_id integer CONSTRAINT accounts_user_user_permissions_permission_id_not_null NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 28312)
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 28274)
-- Name: user_favorite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_favorite (
    id bigint CONSTRAINT accounts_userfavorite_id_not_null NOT NULL,
    created_at timestamp with time zone CONSTRAINT accounts_userfavorite_created_at_not_null NOT NULL,
    recipe_id bigint CONSTRAINT accounts_userfavorite_recipe_id_not_null NOT NULL,
    user_id bigint CONSTRAINT accounts_userfavorite_user_id_not_null NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 28273)
-- Name: accounts_userfavorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userfavorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 28211)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 28210)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 28221)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 28220)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 28201)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 28200)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 28649)
-- Name: cart_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_item (
    id bigint CONSTRAINT cart_cartitem_id_not_null NOT NULL,
    total_amount numeric(8,2) CONSTRAINT cart_cartitem_total_amount_not_null NOT NULL,
    is_checked boolean CONSTRAINT cart_cartitem_is_checked_not_null NOT NULL,
    ingredient_id bigint CONSTRAINT cart_cartitem_ingredient_id_not_null NOT NULL,
    unit_id bigint CONSTRAINT cart_cartitem_unit_id_not_null NOT NULL,
    user_id bigint CONSTRAINT cart_cartitem_user_id_not_null NOT NULL
);


--
-- TOC entry 259 (class 1259 OID 28648)
-- Name: cart_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 28599)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- TOC entry 257 (class 1259 OID 28598)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 28189)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 28188)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 28177)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 28176)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 28775)
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- TOC entry 248 (class 1259 OID 28414)
-- Name: ingredient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredient (
    id bigint CONSTRAINT recipes_ingredient_id_not_null NOT NULL,
    name character varying(255) CONSTRAINT recipes_ingredient_name_not_null NOT NULL,
    category_id bigint CONSTRAINT recipes_ingredient_category_id_not_null NOT NULL
);


--
-- TOC entry 244 (class 1259 OID 28398)
-- Name: ingredient_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredient_category (
    id bigint CONSTRAINT recipes_ingredientcategory_id_not_null NOT NULL,
    name character varying(100) CONSTRAINT recipes_ingredientcategory_name_not_null NOT NULL
);


--
-- TOC entry 266 (class 1259 OID 28732)
-- Name: ingredient_nutrition; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredient_nutrition (
    id bigint NOT NULL,
    base_weight_g smallint CONSTRAINT ingredient_nutrition_base_weight_not_null NOT NULL,
    protein numeric(5,1) NOT NULL,
    fat numeric(5,1) NOT NULL,
    carbs numeric(5,1) NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT ingredient_nutrition_base_weight_check CHECK ((base_weight_g >= 0))
);


--
-- TOC entry 265 (class 1259 OID 28731)
-- Name: ingredient_nutrition_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredient_nutrition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredient_nutrition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 28688)
-- Name: menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu (
    id bigint CONSTRAINT menus_menu_id_not_null NOT NULL,
    period character varying(20) CONSTRAINT menus_menu_period_not_null NOT NULL,
    start_date date CONSTRAINT menus_menu_start_date_not_null NOT NULL,
    user_id bigint CONSTRAINT menus_menu_user_id_not_null NOT NULL
);


--
-- TOC entry 264 (class 1259 OID 28698)
-- Name: menu_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_item (
    id bigint CONSTRAINT menus_menuitem_id_not_null NOT NULL,
    meal_type character varying(50) CONSTRAINT menus_menuitem_meal_type_not_null NOT NULL,
    menu_id bigint CONSTRAINT menus_menuitem_menu_id_not_null NOT NULL,
    recipe_id bigint CONSTRAINT menus_menuitem_recipe_id_not_null NOT NULL,
    day_offset smallint NOT NULL,
    CONSTRAINT menu_item_day_offset_check CHECK ((day_offset >= 0))
);


--
-- TOC entry 261 (class 1259 OID 28687)
-- Name: menus_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 28697)
-- Name: menus_menuitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_menuitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 28422)
-- Name: recipe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe (
    id bigint CONSTRAINT recipes_recipe_id_not_null NOT NULL,
    title character varying(255) CONSTRAINT recipes_recipe_title_not_null NOT NULL,
    image_url character varying(255),
    cook_time integer CONSTRAINT recipes_recipe_cook_time_not_null NOT NULL,
    servings smallint CONSTRAINT recipes_recipe_servings_not_null NOT NULL,
    CONSTRAINT recipe_cook_time_65595d83_check CHECK ((cook_time >= 0)),
    CONSTRAINT recipe_servings_59d4e85c_check CHECK ((servings >= 0))
);


--
-- TOC entry 252 (class 1259 OID 28438)
-- Name: recipe_diet_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_diet_types (
    id bigint CONSTRAINT recipes_recipe_diet_types_id_not_null NOT NULL,
    recipe_id bigint CONSTRAINT recipes_recipe_diet_types_recipe_id_not_null NOT NULL,
    diettype_id bigint CONSTRAINT recipes_recipe_diet_types_diettype_id_not_null NOT NULL
);


--
-- TOC entry 256 (class 1259 OID 28459)
-- Name: recipe_ingredient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_ingredient (
    id bigint CONSTRAINT recipes_recipeingredient_id_not_null NOT NULL,
    amount numeric(8,2) CONSTRAINT recipes_recipeingredient_amount_not_null NOT NULL,
    ingredient_id bigint CONSTRAINT recipes_recipeingredient_ingredient_id_not_null NOT NULL,
    recipe_id bigint CONSTRAINT recipes_recipeingredient_recipe_id_not_null NOT NULL,
    unit_id bigint CONSTRAINT recipes_recipeingredient_unit_id_not_null NOT NULL
);


--
-- TOC entry 254 (class 1259 OID 28447)
-- Name: recipe_step; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_step (
    id bigint CONSTRAINT recipes_recipestep_id_not_null NOT NULL,
    step_number smallint CONSTRAINT recipes_recipestep_step_number_not_null NOT NULL,
    description text CONSTRAINT recipes_recipestep_description_not_null NOT NULL,
    image_url character varying(255),
    recipe_id bigint CONSTRAINT recipes_recipestep_recipe_id_not_null NOT NULL,
    CONSTRAINT recipe_step_step_number_5ec7d168_check CHECK ((step_number >= 0))
);


--
-- TOC entry 247 (class 1259 OID 28413)
-- Name: recipes_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 28397)
-- Name: recipes_ingredientcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredient_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_ingredientcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 28437)
-- Name: recipes_recipe_diet_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_diet_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipe_diet_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 28421)
-- Name: recipes_recipe_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 28458)
-- Name: recipes_recipeingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipeingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 28446)
-- Name: recipes_recipestep_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipestep_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 28406)
-- Name: unit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit (
    id bigint CONSTRAINT recipes_unit_id_not_null NOT NULL,
    name character varying(100) CONSTRAINT recipes_unit_name_not_null NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 28405)
-- Name: recipes_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 28747)
-- Name: unit_convertion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_convertion (
    id bigint NOT NULL,
    grams_per_unit numeric(8,2) NOT NULL,
    ingredient_id bigint NOT NULL,
    unit_id bigint NOT NULL
);


--
-- TOC entry 267 (class 1259 OID 28746)
-- Name: unit_convertion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unit_convertion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_convertion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5211 (class 0 OID 28258)
-- Dependencies: 230
-- Data for Name: allergy; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5207 (class 0 OID 28211)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5209 (class 0 OID 28221)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5205 (class 0 OID 28201)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.auth_permission VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission VALUES (5, 'Can add permission', 3, 'add_permission');
INSERT INTO public.auth_permission VALUES (6, 'Can change permission', 3, 'change_permission');
INSERT INTO public.auth_permission VALUES (7, 'Can delete permission', 3, 'delete_permission');
INSERT INTO public.auth_permission VALUES (8, 'Can view permission', 3, 'view_permission');
INSERT INTO public.auth_permission VALUES (9, 'Can add group', 2, 'add_group');
INSERT INTO public.auth_permission VALUES (10, 'Can change group', 2, 'change_group');
INSERT INTO public.auth_permission VALUES (11, 'Can delete group', 2, 'delete_group');
INSERT INTO public.auth_permission VALUES (12, 'Can view group', 2, 'view_group');
INSERT INTO public.auth_permission VALUES (13, 'Can add content type', 4, 'add_contenttype');
INSERT INTO public.auth_permission VALUES (14, 'Can change content type', 4, 'change_contenttype');
INSERT INTO public.auth_permission VALUES (15, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO public.auth_permission VALUES (16, 'Can view content type', 4, 'view_contenttype');
INSERT INTO public.auth_permission VALUES (17, 'Can add session', 5, 'add_session');
INSERT INTO public.auth_permission VALUES (18, 'Can change session', 5, 'change_session');
INSERT INTO public.auth_permission VALUES (19, 'Can delete session', 5, 'delete_session');
INSERT INTO public.auth_permission VALUES (20, 'Can view session', 5, 'view_session');
INSERT INTO public.auth_permission VALUES (21, 'Can add allergy', 6, 'add_allergy');
INSERT INTO public.auth_permission VALUES (22, 'Can change allergy', 6, 'change_allergy');
INSERT INTO public.auth_permission VALUES (23, 'Can delete allergy', 6, 'delete_allergy');
INSERT INTO public.auth_permission VALUES (24, 'Can view allergy', 6, 'view_allergy');
INSERT INTO public.auth_permission VALUES (25, 'Can add diet type', 7, 'add_diettype');
INSERT INTO public.auth_permission VALUES (26, 'Can change diet type', 7, 'change_diettype');
INSERT INTO public.auth_permission VALUES (27, 'Can delete diet type', 7, 'delete_diettype');
INSERT INTO public.auth_permission VALUES (28, 'Can view diet type', 7, 'view_diettype');
INSERT INTO public.auth_permission VALUES (29, 'Can add user favorite', 9, 'add_userfavorite');
INSERT INTO public.auth_permission VALUES (30, 'Can change user favorite', 9, 'change_userfavorite');
INSERT INTO public.auth_permission VALUES (31, 'Can delete user favorite', 9, 'delete_userfavorite');
INSERT INTO public.auth_permission VALUES (32, 'Can view user favorite', 9, 'view_userfavorite');
INSERT INTO public.auth_permission VALUES (33, 'Can add user', 8, 'add_user');
INSERT INTO public.auth_permission VALUES (34, 'Can change user', 8, 'change_user');
INSERT INTO public.auth_permission VALUES (35, 'Can delete user', 8, 'delete_user');
INSERT INTO public.auth_permission VALUES (36, 'Can view user', 8, 'view_user');
INSERT INTO public.auth_permission VALUES (37, 'Can add ingredient category', 11, 'add_ingredientcategory');
INSERT INTO public.auth_permission VALUES (38, 'Can change ingredient category', 11, 'change_ingredientcategory');
INSERT INTO public.auth_permission VALUES (39, 'Can delete ingredient category', 11, 'delete_ingredientcategory');
INSERT INTO public.auth_permission VALUES (40, 'Can view ingredient category', 11, 'view_ingredientcategory');
INSERT INTO public.auth_permission VALUES (41, 'Can add unit', 16, 'add_unit');
INSERT INTO public.auth_permission VALUES (42, 'Can change unit', 16, 'change_unit');
INSERT INTO public.auth_permission VALUES (43, 'Can delete unit', 16, 'delete_unit');
INSERT INTO public.auth_permission VALUES (44, 'Can view unit', 16, 'view_unit');
INSERT INTO public.auth_permission VALUES (45, 'Can add ingredient', 10, 'add_ingredient');
INSERT INTO public.auth_permission VALUES (46, 'Can change ingredient', 10, 'change_ingredient');
INSERT INTO public.auth_permission VALUES (47, 'Can delete ingredient', 10, 'delete_ingredient');
INSERT INTO public.auth_permission VALUES (48, 'Can view ingredient', 10, 'view_ingredient');
INSERT INTO public.auth_permission VALUES (49, 'Can add recipe', 13, 'add_recipe');
INSERT INTO public.auth_permission VALUES (50, 'Can change recipe', 13, 'change_recipe');
INSERT INTO public.auth_permission VALUES (51, 'Can delete recipe', 13, 'delete_recipe');
INSERT INTO public.auth_permission VALUES (52, 'Can view recipe', 13, 'view_recipe');
INSERT INTO public.auth_permission VALUES (53, 'Can add recipe step', 15, 'add_recipestep');
INSERT INTO public.auth_permission VALUES (54, 'Can change recipe step', 15, 'change_recipestep');
INSERT INTO public.auth_permission VALUES (55, 'Can delete recipe step', 15, 'delete_recipestep');
INSERT INTO public.auth_permission VALUES (56, 'Can view recipe step', 15, 'view_recipestep');
INSERT INTO public.auth_permission VALUES (57, 'Can add recipe ingredient', 14, 'add_recipeingredient');
INSERT INTO public.auth_permission VALUES (58, 'Can change recipe ingredient', 14, 'change_recipeingredient');
INSERT INTO public.auth_permission VALUES (59, 'Can delete recipe ingredient', 14, 'delete_recipeingredient');
INSERT INTO public.auth_permission VALUES (60, 'Can view recipe ingredient', 14, 'view_recipeingredient');
INSERT INTO public.auth_permission VALUES (61, 'Can add ingredient nutrition', 12, 'add_ingredientnutrition');
INSERT INTO public.auth_permission VALUES (62, 'Can change ingredient nutrition', 12, 'change_ingredientnutrition');
INSERT INTO public.auth_permission VALUES (63, 'Can delete ingredient nutrition', 12, 'delete_ingredientnutrition');
INSERT INTO public.auth_permission VALUES (64, 'Can view ingredient nutrition', 12, 'view_ingredientnutrition');
INSERT INTO public.auth_permission VALUES (65, 'Can add unit conversion', 17, 'add_unitconversion');
INSERT INTO public.auth_permission VALUES (66, 'Can change unit conversion', 17, 'change_unitconversion');
INSERT INTO public.auth_permission VALUES (67, 'Can delete unit conversion', 17, 'delete_unitconversion');
INSERT INTO public.auth_permission VALUES (68, 'Can view unit conversion', 17, 'view_unitconversion');
INSERT INTO public.auth_permission VALUES (69, 'Can add menu', 18, 'add_menu');
INSERT INTO public.auth_permission VALUES (70, 'Can change menu', 18, 'change_menu');
INSERT INTO public.auth_permission VALUES (71, 'Can delete menu', 18, 'delete_menu');
INSERT INTO public.auth_permission VALUES (72, 'Can view menu', 18, 'view_menu');
INSERT INTO public.auth_permission VALUES (73, 'Can add menu item', 19, 'add_menuitem');
INSERT INTO public.auth_permission VALUES (74, 'Can change menu item', 19, 'change_menuitem');
INSERT INTO public.auth_permission VALUES (75, 'Can delete menu item', 19, 'delete_menuitem');
INSERT INTO public.auth_permission VALUES (76, 'Can view menu item', 19, 'view_menuitem');
INSERT INTO public.auth_permission VALUES (77, 'Can add cart item', 20, 'add_cartitem');
INSERT INTO public.auth_permission VALUES (78, 'Can change cart item', 20, 'change_cartitem');
INSERT INTO public.auth_permission VALUES (79, 'Can delete cart item', 20, 'delete_cartitem');
INSERT INTO public.auth_permission VALUES (80, 'Can view cart item', 20, 'view_cartitem');


--
-- TOC entry 5241 (class 0 OID 28649)
-- Dependencies: 260
-- Data for Name: cart_item; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5213 (class 0 OID 28266)
-- Dependencies: 232
-- Data for Name: diet_type; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5239 (class 0 OID 28599)
-- Dependencies: 258
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5203 (class 0 OID 28189)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.django_content_type VALUES (1, 'admin', 'logentry');
INSERT INTO public.django_content_type VALUES (2, 'auth', 'group');
INSERT INTO public.django_content_type VALUES (3, 'auth', 'permission');
INSERT INTO public.django_content_type VALUES (4, 'contenttypes', 'contenttype');
INSERT INTO public.django_content_type VALUES (5, 'sessions', 'session');
INSERT INTO public.django_content_type VALUES (6, 'accounts', 'allergy');
INSERT INTO public.django_content_type VALUES (7, 'accounts', 'diettype');
INSERT INTO public.django_content_type VALUES (8, 'accounts', 'user');
INSERT INTO public.django_content_type VALUES (9, 'accounts', 'userfavorite');
INSERT INTO public.django_content_type VALUES (10, 'recipes', 'ingredient');
INSERT INTO public.django_content_type VALUES (11, 'recipes', 'ingredientcategory');
INSERT INTO public.django_content_type VALUES (12, 'recipes', 'ingredientnutrition');
INSERT INTO public.django_content_type VALUES (13, 'recipes', 'recipe');
INSERT INTO public.django_content_type VALUES (14, 'recipes', 'recipeingredient');
INSERT INTO public.django_content_type VALUES (15, 'recipes', 'recipestep');
INSERT INTO public.django_content_type VALUES (16, 'recipes', 'unit');
INSERT INTO public.django_content_type VALUES (17, 'recipes', 'unitconversion');
INSERT INTO public.django_content_type VALUES (18, 'menus', 'menu');
INSERT INTO public.django_content_type VALUES (19, 'menus', 'menuitem');
INSERT INTO public.django_content_type VALUES (20, 'cart', 'cartitem');


--
-- TOC entry 5201 (class 0 OID 28177)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.django_migrations VALUES (1, 'contenttypes', '0001_initial', '2026-03-10 20:09:44.63527+03');
INSERT INTO public.django_migrations VALUES (2, 'contenttypes', '0002_remove_content_type_name', '2026-03-10 20:09:44.647217+03');
INSERT INTO public.django_migrations VALUES (3, 'auth', '0001_initial', '2026-03-10 20:09:44.678681+03');
INSERT INTO public.django_migrations VALUES (4, 'auth', '0002_alter_permission_name_max_length', '2026-03-10 20:09:44.683418+03');
INSERT INTO public.django_migrations VALUES (5, 'auth', '0003_alter_user_email_max_length', '2026-03-10 20:09:44.688755+03');
INSERT INTO public.django_migrations VALUES (6, 'auth', '0004_alter_user_username_opts', '2026-03-10 20:09:44.693335+03');
INSERT INTO public.django_migrations VALUES (7, 'auth', '0005_alter_user_last_login_null', '2026-03-10 20:09:44.698241+03');
INSERT INTO public.django_migrations VALUES (8, 'auth', '0006_require_contenttypes_0002', '2026-03-10 20:09:44.699673+03');
INSERT INTO public.django_migrations VALUES (9, 'auth', '0007_alter_validators_add_error_messages', '2026-03-10 20:09:44.705047+03');
INSERT INTO public.django_migrations VALUES (10, 'auth', '0008_alter_user_username_max_length', '2026-03-10 20:09:44.709675+03');
INSERT INTO public.django_migrations VALUES (11, 'auth', '0009_alter_user_last_name_max_length', '2026-03-10 20:09:44.714426+03');
INSERT INTO public.django_migrations VALUES (12, 'auth', '0010_alter_group_name_max_length', '2026-03-10 20:09:44.722788+03');
INSERT INTO public.django_migrations VALUES (13, 'auth', '0011_update_proxy_permissions', '2026-03-10 20:09:44.727623+03');
INSERT INTO public.django_migrations VALUES (14, 'auth', '0012_alter_user_first_name_max_length', '2026-03-10 20:09:44.732574+03');
INSERT INTO public.django_migrations VALUES (15, 'accounts', '0001_initial', '2026-03-10 20:09:44.793998+03');
INSERT INTO public.django_migrations VALUES (16, 'recipes', '0001_initial', '2026-03-10 20:09:44.87087+03');
INSERT INTO public.django_migrations VALUES (17, 'recipes', '0002_alter_ingredient_category_alter_ingredient_unit_and_more', '2026-03-10 20:09:44.97185+03');
INSERT INTO public.django_migrations VALUES (18, 'recipes', '0003_alter_ingredient_name', '2026-03-10 20:09:44.978296+03');
INSERT INTO public.django_migrations VALUES (19, 'accounts', '0002_initial', '2026-03-10 20:09:45.009992+03');
INSERT INTO public.django_migrations VALUES (20, 'accounts', '0003_alter_user_options_user_created_at_and_more', '2026-03-10 20:09:45.116697+03');
INSERT INTO public.django_migrations VALUES (21, 'accounts', '0004_alter_user_password', '2026-03-10 20:09:45.12699+03');
INSERT INTO public.django_migrations VALUES (22, 'accounts', '0005_alter_userfavorite_unique_together', '2026-03-10 20:09:45.14655+03');
INSERT INTO public.django_migrations VALUES (23, 'accounts', '0006_alter_allergy_options_alter_diettype_options_and_more', '2026-03-10 20:09:45.23472+03');
INSERT INTO public.django_migrations VALUES (24, 'admin', '0001_initial', '2026-03-10 20:09:45.257407+03');
INSERT INTO public.django_migrations VALUES (25, 'admin', '0002_logentry_remove_auto_add', '2026-03-10 20:09:45.267335+03');
INSERT INTO public.django_migrations VALUES (26, 'admin', '0003_logentry_add_action_flag_choices', '2026-03-10 20:09:45.276031+03');
INSERT INTO public.django_migrations VALUES (27, 'recipes', '0004_alter_ingredient_options_and_more', '2026-03-10 20:09:45.369598+03');
INSERT INTO public.django_migrations VALUES (28, 'cart', '0001_initial', '2026-03-10 20:09:45.398456+03');
INSERT INTO public.django_migrations VALUES (29, 'cart', '0002_alter_cartitem_is_checked_alter_cartitem_unit_and_more', '2026-03-10 20:09:45.439282+03');
INSERT INTO public.django_migrations VALUES (30, 'cart', '0003_alter_cartitem_total_amount_and_more', '2026-03-10 20:09:45.48473+03');
INSERT INTO public.django_migrations VALUES (31, 'menus', '0001_initial', '2026-03-10 20:09:45.530563+03');
INSERT INTO public.django_migrations VALUES (32, 'menus', '0002_alter_menu_period_alter_menuitem_meal_type_and_more', '2026-03-10 20:09:45.606526+03');
INSERT INTO public.django_migrations VALUES (33, 'menus', '0003_remove_menuitem_day_menuitem_day_offset_and_more', '2026-03-10 20:09:45.646013+03');
INSERT INTO public.django_migrations VALUES (34, 'menus', '0004_alter_menu_period_alter_menuitem_meal_type', '2026-03-10 20:09:45.663811+03');
INSERT INTO public.django_migrations VALUES (35, 'recipes', '0005_remove_ingredient_unit_remove_recipe_calories_and_more', '2026-03-10 20:09:45.765506+03');
INSERT INTO public.django_migrations VALUES (36, 'recipes', '0006_rename_base_weight_ingredientnutrition_base_weight_g', '2026-03-10 20:09:45.771454+03');
INSERT INTO public.django_migrations VALUES (37, 'sessions', '0001_initial', '2026-03-10 20:09:45.779947+03');


--
-- TOC entry 5250 (class 0 OID 28775)
-- Dependencies: 269
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5229 (class 0 OID 28414)
-- Dependencies: 248
-- Data for Name: ingredient; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5225 (class 0 OID 28398)
-- Dependencies: 244
-- Data for Name: ingredient_category; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5247 (class 0 OID 28732)
-- Dependencies: 266
-- Data for Name: ingredient_nutrition; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5243 (class 0 OID 28688)
-- Dependencies: 262
-- Data for Name: menu; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5245 (class 0 OID 28698)
-- Dependencies: 264
-- Data for Name: menu_item; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5231 (class 0 OID 28422)
-- Dependencies: 250
-- Data for Name: recipe; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5233 (class 0 OID 28438)
-- Dependencies: 252
-- Data for Name: recipe_diet_types; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5237 (class 0 OID 28459)
-- Dependencies: 256
-- Data for Name: recipe_ingredient; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5235 (class 0 OID 28447)
-- Dependencies: 254
-- Data for Name: recipe_step; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5227 (class 0 OID 28406)
-- Dependencies: 246
-- Data for Name: unit; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5249 (class 0 OID 28747)
-- Dependencies: 268
-- Data for Name: unit_convertion; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5217 (class 0 OID 28282)
-- Dependencies: 236
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5223 (class 0 OID 28322)
-- Dependencies: 242
-- Data for Name: user_allergies; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5215 (class 0 OID 28274)
-- Dependencies: 234
-- Data for Name: user_favorite; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5219 (class 0 OID 28304)
-- Dependencies: 238
-- Data for Name: user_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5221 (class 0 OID 28313)
-- Dependencies: 240
-- Data for Name: user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5256 (class 0 OID 0)
-- Dependencies: 229
-- Name: accounts_allergy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_allergy_id_seq', 1, false);


--
-- TOC entry 5257 (class 0 OID 0)
-- Dependencies: 231
-- Name: accounts_diettype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_diettype_id_seq', 1, false);


--
-- TOC entry 5258 (class 0 OID 0)
-- Dependencies: 241
-- Name: accounts_user_allergies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_allergies_id_seq', 1, false);


--
-- TOC entry 5259 (class 0 OID 0)
-- Dependencies: 237
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- TOC entry 5260 (class 0 OID 0)
-- Dependencies: 235
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 1, false);


--
-- TOC entry 5261 (class 0 OID 0)
-- Dependencies: 239
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5262 (class 0 OID 0)
-- Dependencies: 233
-- Name: accounts_userfavorite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_userfavorite_id_seq', 1, false);


--
-- TOC entry 5263 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5264 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5265 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- TOC entry 5266 (class 0 OID 0)
-- Dependencies: 259
-- Name: cart_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cart_cartitem_id_seq', 1, false);


--
-- TOC entry 5267 (class 0 OID 0)
-- Dependencies: 257
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5268 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- TOC entry 5269 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 37, true);


--
-- TOC entry 5270 (class 0 OID 0)
-- Dependencies: 265
-- Name: ingredient_nutrition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ingredient_nutrition_id_seq', 1, false);


--
-- TOC entry 5271 (class 0 OID 0)
-- Dependencies: 261
-- Name: menus_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.menus_menu_id_seq', 1, false);


--
-- TOC entry 5272 (class 0 OID 0)
-- Dependencies: 263
-- Name: menus_menuitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.menus_menuitem_id_seq', 1, false);


--
-- TOC entry 5273 (class 0 OID 0)
-- Dependencies: 247
-- Name: recipes_ingredient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_ingredient_id_seq', 1, false);


--
-- TOC entry 5274 (class 0 OID 0)
-- Dependencies: 243
-- Name: recipes_ingredientcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_ingredientcategory_id_seq', 1, false);


--
-- TOC entry 5275 (class 0 OID 0)
-- Dependencies: 251
-- Name: recipes_recipe_diet_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_recipe_diet_types_id_seq', 1, false);


--
-- TOC entry 5276 (class 0 OID 0)
-- Dependencies: 249
-- Name: recipes_recipe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_recipe_id_seq', 1, false);


--
-- TOC entry 5277 (class 0 OID 0)
-- Dependencies: 255
-- Name: recipes_recipeingredient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_recipeingredient_id_seq', 1, false);


--
-- TOC entry 5278 (class 0 OID 0)
-- Dependencies: 253
-- Name: recipes_recipestep_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_recipestep_id_seq', 1, false);


--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 245
-- Name: recipes_unit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_unit_id_seq', 1, false);


--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 267
-- Name: unit_convertion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.unit_convertion_id_seq', 1, false);


--
-- TOC entry 4909 (class 2606 OID 28566)
-- Name: allergy accounts_allergy_name_0ba4185d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allergy
    ADD CONSTRAINT accounts_allergy_name_0ba4185d_uniq UNIQUE (name);


--
-- TOC entry 4911 (class 2606 OID 28264)
-- Name: allergy accounts_allergy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allergy
    ADD CONSTRAINT accounts_allergy_pkey PRIMARY KEY (id);


--
-- TOC entry 4914 (class 2606 OID 28569)
-- Name: diet_type accounts_diettype_name_7985f8b5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diet_type
    ADD CONSTRAINT accounts_diettype_name_7985f8b5_uniq UNIQUE (name);


--
-- TOC entry 4916 (class 2606 OID 28272)
-- Name: diet_type accounts_diettype_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diet_type
    ADD CONSTRAINT accounts_diettype_pkey PRIMARY KEY (id);


--
-- TOC entry 4947 (class 2606 OID 28329)
-- Name: user_allergies accounts_user_allergies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_allergies
    ADD CONSTRAINT accounts_user_allergies_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 28370)
-- Name: user_allergies accounts_user_allergies_user_id_allergy_id_a58c3b03_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_allergies
    ADD CONSTRAINT accounts_user_allergies_user_id_allergy_id_a58c3b03_uniq UNIQUE (user_id, allergy_id);


--
-- TOC entry 4926 (class 2606 OID 28302)
-- Name: user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- TOC entry 4935 (class 2606 OID 28311)
-- Name: user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4938 (class 2606 OID 28342)
-- Name: user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4928 (class 2606 OID 28298)
-- Name: user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4940 (class 2606 OID 28356)
-- Name: user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4943 (class 2606 OID 28320)
-- Name: user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4931 (class 2606 OID 28300)
-- Name: user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- TOC entry 4918 (class 2606 OID 28280)
-- Name: user_favorite accounts_userfavorite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT accounts_userfavorite_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 28254)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4903 (class 2606 OID 28239)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4906 (class 2606 OID 28228)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 28217)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 28230)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4895 (class 2606 OID 28209)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4994 (class 2606 OID 28658)
-- Name: cart_item cart_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_cartitem_pkey PRIMARY KEY (id);


--
-- TOC entry 5000 (class 2606 OID 28684)
-- Name: cart_item cart_item_user_id_ingredient_id_34db7293_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_user_id_ingredient_id_34db7293_uniq UNIQUE (user_id, ingredient_id);


--
-- TOC entry 4990 (class 2606 OID 28612)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 28199)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4890 (class 2606 OID 28197)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 28187)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5021 (class 2606 OID 28784)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4963 (class 2606 OID 28547)
-- Name: ingredient ingredient_name_4414e639_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT ingredient_name_4414e639_uniq UNIQUE (name);


--
-- TOC entry 5010 (class 2606 OID 28745)
-- Name: ingredient_nutrition ingredient_nutrition_ingredient_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_nutrition
    ADD CONSTRAINT ingredient_nutrition_ingredient_id_key UNIQUE (ingredient_id);


--
-- TOC entry 5012 (class 2606 OID 28743)
-- Name: ingredient_nutrition ingredient_nutrition_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_nutrition
    ADD CONSTRAINT ingredient_nutrition_pkey PRIMARY KEY (id);


--
-- TOC entry 5002 (class 2606 OID 28696)
-- Name: menu menus_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menus_menu_pkey PRIMARY KEY (id);


--
-- TOC entry 5007 (class 2606 OID 28707)
-- Name: menu_item menus_menuitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item
    ADD CONSTRAINT menus_menuitem_pkey PRIMARY KEY (id);


--
-- TOC entry 4982 (class 2606 OID 28730)
-- Name: recipe_ingredient recipe_ingredient_recipe_id_ingredient_id_unit_id_0772a314_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredient
    ADD CONSTRAINT recipe_ingredient_recipe_id_ingredient_id_unit_id_0772a314_uniq UNIQUE (recipe_id, ingredient_id, unit_id);


--
-- TOC entry 4966 (class 2606 OID 28420)
-- Name: ingredient recipes_ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT recipes_ingredient_pkey PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 28531)
-- Name: ingredient_category recipes_ingredientcategory_name_31d394aa_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_category
    ADD CONSTRAINT recipes_ingredientcategory_name_31d394aa_uniq UNIQUE (name);


--
-- TOC entry 4955 (class 2606 OID 28404)
-- Name: ingredient_category recipes_ingredientcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_category
    ADD CONSTRAINT recipes_ingredientcategory_pkey PRIMARY KEY (id);


--
-- TOC entry 4972 (class 2606 OID 28445)
-- Name: recipe_diet_types recipes_recipe_diet_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_diet_types
    ADD CONSTRAINT recipes_recipe_diet_types_pkey PRIMARY KEY (id);


--
-- TOC entry 4975 (class 2606 OID 28481)
-- Name: recipe_diet_types recipes_recipe_diet_types_recipe_id_diettype_id_b153c3da_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_diet_types
    ADD CONSTRAINT recipes_recipe_diet_types_recipe_id_diettype_id_b153c3da_uniq UNIQUE (recipe_id, diettype_id);


--
-- TOC entry 4969 (class 2606 OID 28436)
-- Name: recipe recipes_recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT recipes_recipe_pkey PRIMARY KEY (id);


--
-- TOC entry 4985 (class 2606 OID 28467)
-- Name: recipe_ingredient recipes_recipeingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredient
    ADD CONSTRAINT recipes_recipeingredient_pkey PRIMARY KEY (id);


--
-- TOC entry 4977 (class 2606 OID 28457)
-- Name: recipe_step recipes_recipestep_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_step
    ADD CONSTRAINT recipes_recipestep_pkey PRIMARY KEY (id);


--
-- TOC entry 4980 (class 2606 OID 28636)
-- Name: recipe_step recipes_recipestep_recipe_id_step_number_ada55a70_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_step
    ADD CONSTRAINT recipes_recipestep_recipe_id_step_number_ada55a70_uniq UNIQUE (recipe_id, step_number);


--
-- TOC entry 4958 (class 2606 OID 28540)
-- Name: unit recipes_unit_name_906c0dee_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT recipes_unit_name_906c0dee_uniq UNIQUE (name);


--
-- TOC entry 4960 (class 2606 OID 28412)
-- Name: unit recipes_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT recipes_unit_pkey PRIMARY KEY (id);


--
-- TOC entry 5015 (class 2606 OID 28762)
-- Name: unit_convertion unit_convertion_ingredient_id_unit_id_92575f7c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_convertion
    ADD CONSTRAINT unit_convertion_ingredient_id_unit_id_92575f7c_uniq UNIQUE (ingredient_id, unit_id);


--
-- TOC entry 5017 (class 2606 OID 28755)
-- Name: unit_convertion unit_convertion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_convertion
    ADD CONSTRAINT unit_convertion_pkey PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 28579)
-- Name: user_favorite user_favorite_user_id_recipe_id_d7746a8a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT user_favorite_user_id_recipe_id_d7746a8a_uniq UNIQUE (user_id, recipe_id);


--
-- TOC entry 4907 (class 1259 OID 28567)
-- Name: accounts_allergy_name_0ba4185d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_allergy_name_0ba4185d_like ON public.allergy USING btree (name varchar_pattern_ops);


--
-- TOC entry 4912 (class 1259 OID 28570)
-- Name: accounts_diettype_name_7985f8b5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_diettype_name_7985f8b5_like ON public.diet_type USING btree (name varchar_pattern_ops);


--
-- TOC entry 4945 (class 1259 OID 28382)
-- Name: accounts_user_allergies_allergy_id_fac9542b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_allergies_allergy_id_fac9542b ON public.user_allergies USING btree (allergy_id);


--
-- TOC entry 4950 (class 1259 OID 28381)
-- Name: accounts_user_allergies_user_id_ce633fa4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_allergies_user_id_ce633fa4 ON public.user_allergies USING btree (user_id);


--
-- TOC entry 4924 (class 1259 OID 28340)
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_email_b2644a56_like ON public."user" USING btree (email varchar_pattern_ops);


--
-- TOC entry 4933 (class 1259 OID 28354)
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.user_groups USING btree (group_id);


--
-- TOC entry 4936 (class 1259 OID 28353)
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.user_groups USING btree (user_id);


--
-- TOC entry 4941 (class 1259 OID 28368)
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.user_user_permissions USING btree (permission_id);


--
-- TOC entry 4944 (class 1259 OID 28367)
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.user_user_permissions USING btree (user_id);


--
-- TOC entry 4929 (class 1259 OID 28339)
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_username_6088629e_like ON public."user" USING btree (username varchar_pattern_ops);


--
-- TOC entry 4919 (class 1259 OID 28561)
-- Name: accounts_userfavorite_recipe_id_485b6886; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_userfavorite_recipe_id_485b6886 ON public.user_favorite USING btree (recipe_id);


--
-- TOC entry 4920 (class 1259 OID 28562)
-- Name: accounts_userfavorite_user_id_88d09a92; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_userfavorite_user_id_88d09a92 ON public.user_favorite USING btree (user_id);


--
-- TOC entry 4896 (class 1259 OID 28255)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4901 (class 1259 OID 28250)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4904 (class 1259 OID 28251)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4891 (class 1259 OID 28236)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4992 (class 1259 OID 28674)
-- Name: cart_cartitem_ingredient_id_2424bcf1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cart_cartitem_ingredient_id_2424bcf1 ON public.cart_item USING btree (ingredient_id);


--
-- TOC entry 4995 (class 1259 OID 28675)
-- Name: cart_cartitem_unit_id_e7152baa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cart_cartitem_unit_id_e7152baa ON public.cart_item USING btree (unit_id);


--
-- TOC entry 4996 (class 1259 OID 28676)
-- Name: cart_cartitem_user_id_292943b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cart_cartitem_user_id_292943b8 ON public.cart_item USING btree (user_id);


--
-- TOC entry 4997 (class 1259 OID 28686)
-- Name: cart_item_is_chec_71a2a4_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cart_item_is_chec_71a2a4_idx ON public.cart_item USING btree (is_checked);


--
-- TOC entry 4998 (class 1259 OID 28685)
-- Name: cart_item_user_id_7a97d7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cart_item_user_id_7a97d7_idx ON public.cart_item USING btree (user_id, ingredient_id);


--
-- TOC entry 4988 (class 1259 OID 28623)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4991 (class 1259 OID 28624)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5019 (class 1259 OID 28786)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5022 (class 1259 OID 28785)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4961 (class 1259 OID 28548)
-- Name: ingredient_name_4414e639_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ingredient_name_4414e639_like ON public.ingredient USING btree (name varchar_pattern_ops);


--
-- TOC entry 5004 (class 1259 OID 28728)
-- Name: menu_day_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX menu_day_idx ON public.menu_item USING btree (menu_id, day_offset);


--
-- TOC entry 5003 (class 1259 OID 28713)
-- Name: menus_menu_user_id_1778f4a7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX menus_menu_user_id_1778f4a7 ON public.menu USING btree (user_id);


--
-- TOC entry 5005 (class 1259 OID 28724)
-- Name: menus_menuitem_menu_id_9d369230; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX menus_menuitem_menu_id_9d369230 ON public.menu_item USING btree (menu_id);


--
-- TOC entry 5008 (class 1259 OID 28725)
-- Name: menus_menuitem_recipe_id_6771db05; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX menus_menuitem_recipe_id_6771db05 ON public.menu_item USING btree (recipe_id);


--
-- TOC entry 4967 (class 1259 OID 28647)
-- Name: recipe_title_2658bf_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipe_title_2658bf_idx ON public.recipe USING btree (title);


--
-- TOC entry 4964 (class 1259 OID 28478)
-- Name: recipes_ingredient_category_id_d6314e97; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_ingredient_category_id_d6314e97 ON public.ingredient USING btree (category_id);


--
-- TOC entry 4951 (class 1259 OID 28532)
-- Name: recipes_ingredientcategory_name_31d394aa_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_ingredientcategory_name_31d394aa_like ON public.ingredient_category USING btree (name varchar_pattern_ops);


--
-- TOC entry 4970 (class 1259 OID 28493)
-- Name: recipes_recipe_diet_types_diettype_id_6a39bb11; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipe_diet_types_diettype_id_6a39bb11 ON public.recipe_diet_types USING btree (diettype_id);


--
-- TOC entry 4973 (class 1259 OID 28492)
-- Name: recipes_recipe_diet_types_recipe_id_c29f53a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipe_diet_types_recipe_id_c29f53a1 ON public.recipe_diet_types USING btree (recipe_id);


--
-- TOC entry 4983 (class 1259 OID 28515)
-- Name: recipes_recipeingredient_ingredient_id_0efc0df1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipeingredient_ingredient_id_0efc0df1 ON public.recipe_ingredient USING btree (ingredient_id);


--
-- TOC entry 4986 (class 1259 OID 28516)
-- Name: recipes_recipeingredient_recipe_id_76423229; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipeingredient_recipe_id_76423229 ON public.recipe_ingredient USING btree (recipe_id);


--
-- TOC entry 4987 (class 1259 OID 28517)
-- Name: recipes_recipeingredient_unit_id_23d6437a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipeingredient_unit_id_23d6437a ON public.recipe_ingredient USING btree (unit_id);


--
-- TOC entry 4978 (class 1259 OID 28499)
-- Name: recipes_recipestep_recipe_id_f5329783; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipestep_recipe_id_f5329783 ON public.recipe_step USING btree (recipe_id);


--
-- TOC entry 4956 (class 1259 OID 28541)
-- Name: recipes_unit_name_906c0dee_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_unit_name_906c0dee_like ON public.unit USING btree (name varchar_pattern_ops);


--
-- TOC entry 5013 (class 1259 OID 28773)
-- Name: unit_convertion_ingredient_id_6fc18c88; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX unit_convertion_ingredient_id_6fc18c88 ON public.unit_convertion USING btree (ingredient_id);


--
-- TOC entry 5018 (class 1259 OID 28774)
-- Name: unit_convertion_unit_id_9c7e6c55; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX unit_convertion_unit_id_9c7e6c55 ON public.unit_convertion USING btree (unit_id);


--
-- TOC entry 4932 (class 1259 OID 28597)
-- Name: user_diet_type_id_39741f17; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_diet_type_id_39741f17 ON public."user" USING btree (diet_type_id);


--
-- TOC entry 4921 (class 1259 OID 28596)
-- Name: user_favori_user_id_0b5b8f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_favori_user_id_0b5b8f_idx ON public.user_favorite USING btree (user_id, created_at);


--
-- TOC entry 5033 (class 2606 OID 28376)
-- Name: user_allergies accounts_user_allerg_allergy_id_fac9542b_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_allergies
    ADD CONSTRAINT accounts_user_allerg_allergy_id_fac9542b_fk_accounts_ FOREIGN KEY (allergy_id) REFERENCES public.allergy(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5034 (class 2606 OID 28371)
-- Name: user_allergies accounts_user_allergies_user_id_ce633fa4_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_allergies
    ADD CONSTRAINT accounts_user_allergies_user_id_ce633fa4_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5029 (class 2606 OID 28348)
-- Name: user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5030 (class 2606 OID 28343)
-- Name: user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5031 (class 2606 OID 28362)
-- Name: user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5032 (class 2606 OID 28357)
-- Name: user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5026 (class 2606 OID 28550)
-- Name: user_favorite accounts_userfavorite_recipe_id_485b6886_fk_recipe_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT accounts_userfavorite_recipe_id_485b6886_fk_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5027 (class 2606 OID 28556)
-- Name: user_favorite accounts_userfavorite_user_id_88d09a92_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT accounts_userfavorite_user_id_88d09a92_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5024 (class 2606 OID 28245)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5025 (class 2606 OID 28240)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5023 (class 2606 OID 28231)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5044 (class 2606 OID 28659)
-- Name: cart_item cart_cartitem_ingredient_id_2424bcf1_fk_ingredient_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_cartitem_ingredient_id_2424bcf1_fk_ingredient_id FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5045 (class 2606 OID 28678)
-- Name: cart_item cart_cartitem_unit_id_e7152baa_fk_unit_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_cartitem_unit_id_e7152baa_fk_unit_id FOREIGN KEY (unit_id) REFERENCES public.unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5046 (class 2606 OID 28669)
-- Name: cart_item cart_cartitem_user_id_292943b8_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_cartitem_user_id_292943b8_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5042 (class 2606 OID 28613)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5043 (class 2606 OID 28618)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5050 (class 2606 OID 28756)
-- Name: ingredient_nutrition ingredient_nutrition_ingredient_id_9b7d5cd3_fk_ingredient_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient_nutrition
    ADD CONSTRAINT ingredient_nutrition_ingredient_id_9b7d5cd3_fk_ingredient_id FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5047 (class 2606 OID 28708)
-- Name: menu menus_menu_user_id_1778f4a7_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menus_menu_user_id_1778f4a7_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5048 (class 2606 OID 28714)
-- Name: menu_item menus_menuitem_menu_id_9d369230_fk_menus_menu_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item
    ADD CONSTRAINT menus_menuitem_menu_id_9d369230_fk_menus_menu_id FOREIGN KEY (menu_id) REFERENCES public.menu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5049 (class 2606 OID 28719)
-- Name: menu_item menus_menuitem_recipe_id_6771db05_fk_recipe_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item
    ADD CONSTRAINT menus_menuitem_recipe_id_6771db05_fk_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5035 (class 2606 OID 28519)
-- Name: ingredient recipes_ingredient_category_id_d6314e97_fk_recipes_i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT recipes_ingredient_category_id_d6314e97_fk_recipes_i FOREIGN KEY (category_id) REFERENCES public.ingredient_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5036 (class 2606 OID 28487)
-- Name: recipe_diet_types recipes_recipe_diet__diettype_id_6a39bb11_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_diet_types
    ADD CONSTRAINT recipes_recipe_diet__diettype_id_6a39bb11_fk_accounts_ FOREIGN KEY (diettype_id) REFERENCES public.diet_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5037 (class 2606 OID 28482)
-- Name: recipe_diet_types recipes_recipe_diet__recipe_id_c29f53a1_fk_recipes_r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_diet_types
    ADD CONSTRAINT recipes_recipe_diet__recipe_id_c29f53a1_fk_recipes_r FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5039 (class 2606 OID 28500)
-- Name: recipe_ingredient recipes_recipeingred_ingredient_id_0efc0df1_fk_recipes_i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredient
    ADD CONSTRAINT recipes_recipeingred_ingredient_id_0efc0df1_fk_recipes_i FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5040 (class 2606 OID 28505)
-- Name: recipe_ingredient recipes_recipeingred_recipe_id_76423229_fk_recipes_r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredient
    ADD CONSTRAINT recipes_recipeingred_recipe_id_76423229_fk_recipes_r FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5041 (class 2606 OID 28534)
-- Name: recipe_ingredient recipes_recipeingredient_unit_id_23d6437a_fk_recipes_unit_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredient
    ADD CONSTRAINT recipes_recipeingredient_unit_id_23d6437a_fk_recipes_unit_id FOREIGN KEY (unit_id) REFERENCES public.unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5038 (class 2606 OID 28494)
-- Name: recipe_step recipes_recipestep_recipe_id_f5329783_fk_recipes_recipe_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_step
    ADD CONSTRAINT recipes_recipestep_recipe_id_f5329783_fk_recipes_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5051 (class 2606 OID 28763)
-- Name: unit_convertion unit_convertion_ingredient_id_6fc18c88_fk_ingredient_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_convertion
    ADD CONSTRAINT unit_convertion_ingredient_id_6fc18c88_fk_ingredient_id FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5052 (class 2606 OID 28768)
-- Name: unit_convertion unit_convertion_unit_id_9c7e6c55_fk_unit_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_convertion
    ADD CONSTRAINT unit_convertion_unit_id_9c7e6c55_fk_unit_id FOREIGN KEY (unit_id) REFERENCES public.unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5028 (class 2606 OID 28580)
-- Name: user user_diet_type_id_39741f17_fk_diet_type_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_diet_type_id_39741f17_fk_diet_type_id FOREIGN KEY (diet_type_id) REFERENCES public.diet_type(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-03-10 20:10:28

--
-- PostgreSQL database dump complete
--
