# Generated by Django 6.0.3 on 2026-03-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ingredients', to='recipes.ingredientcategory'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ingredients', to='recipes.unit'),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='recipestep',
            unique_together={('recipe', 'step_number')},
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
        migrations.AlterModelTable(
            name='ingredientcategory',
            table='ingredient_category',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table='recipe_ingredient',
        ),
        migrations.AlterModelTable(
            name='recipestep',
            table='recipe_step',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
