# Generated by Django 6.0.3 on 2026-03-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredient_unit_remove_recipe_calories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientnutrition',
            old_name='base_weight',
            new_name='base_weight_g',
        ),
    ]
