# Generated by Django 6.0.3 on 2026-03-11 15:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_allergy_options_alter_diettype_options_and_more'),
        ('recipes', '0006_rename_base_weight_ingredientnutrition_base_weight_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_carbs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_fats',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_proteins',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_weight_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['total_calories'], name='recipe_total_c_13373a_idx'),
        ),
    ]
