# Generated by Django 6.0.3 on 2026-03-11 17:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_base_weight_ingredientnutrition_base_weight_g'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipestep',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'unit'), name='unique_recipe_ingredient_unit'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe', 'step_number'), name='unique_recipe_step_number'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('ingredient', 'unit'), name='unique_ingredient_unit_conversion'),
        ),
    ]
