# Generated by Django 6.0.3 on 2026-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_audit_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='timer',
            field=models.IntegerField(blank=True, help_text='Время таймера в минутах', null=True),
        ),
    ]
