# Generated by Django 6.0.3 on 2026-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_mealtype_alter_menuitem_meal_type'),
        ('recipes', '0009_recipestep_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='meal_types',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='menus.mealtype'),
        ),
    ]
