# Generated by Django 6.0.3 on 2026-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfavorite_unique_together_and_more'),
        ('recipes', '0010_recipe_meal_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergies',
            field=models.ManyToManyField(related_name='ingredients', to='accounts.allergy'),
        ),
    ]
