# Generated by Django 6.0.3 on 2026-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_mealtype_order'),
        ('recipes', '0010_recipestep_meal_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='meal_types',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_types',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='menus.mealtype'),
        ),
    ]
