# Generated by Django 6.0.3 on 2026-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfavorite_unique_together_and_more'),
        ('recipes', '0011_ingredient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='accounts.allergy'),
        ),
    ]
