# Generated by Django 6.0.3 on 2026-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_allergies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория ингредиента', 'verbose_name_plural': 'Категории ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='ingredientnutrition',
            options={'verbose_name': 'Пищевая ценность ингредиента', 'verbose_name_plural': 'Пищевые ценности ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['step_number'], 'verbose_name': 'Шаг притовления рецепта', 'verbose_name_plural': 'Шаги приготовления рецептов'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'ordering': ['grams_per_unit'], 'verbose_name': 'Конвертация единицы измерения', 'verbose_name_plural': 'Конвертации единиц измерения'},
        ),
    ]
