# Generated by Django 6.0.3 on 2026-03-20 09:39

import app.recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.recipes.models._get_recipe_photopath),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.recipes.models._get_recipe_step_photopath),
        ),
    ]
