# Generated by Django 6.0.3 on 2026-03-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_image_url_alter_recipestep_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'ordering': ['ingredient__name', 'amount_per_unit'], 'verbose_name': 'Конвертация единицы измерения', 'verbose_name_plural': 'Конвертации единиц измерения'},
        ),
        migrations.RemoveConstraint(
            model_name='unitconversion',
            name='unique_ingredient_unit_conversion',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='base_weight_g',
        ),
        migrations.AddField(
            model_name='ingredientnutrition',
            name='base_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='ingredient_nutritions', to='recipes.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientnutrition',
            name='base_weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Масса, для которой указаны КБЖУ (в базовых единицах)'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='amount_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Количество в базовой единице', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='base_unit',
            field=models.ForeignKey(default=1, help_text='Базовая единица, в которую конвертируется', on_delete=django.db.models.deletion.RESTRICT, related_name='conversions_to', to='recipes.unit'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('ingredient', 'unit', 'base_unit'), name='unique_ingredient_unit_conversion'),
        ),
        migrations.RemoveField(
            model_name='unitconversion',
            name='grams_per_unit',
        ),
    ]
