# Generated by Django 6.0.3 on 2026-03-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_unitconversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='add_to_cart',
            field=models.BooleanField(default=True),
        ),
    ]
