# Generated by Django 6.0.3 on 2026-03-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_ingredient_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='add_to_cart',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='can_be_added_to_cart',
            field=models.BooleanField(default=True, help_text='Должен ли ингредиент добавляться в корзину'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='base_unit',
            field=models.ForeignKey(help_text='Единица, в которую конвертируется', on_delete=django.db.models.deletion.RESTRICT, related_name='conversions_to', to='recipes.unit'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_other_units', to='recipes.unit'),
        ),
    ]
