# Generated by Django 6.0.3 on 2026-03-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_ingredient_add_to_cart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unitconversion',
            name='unique_ingredient_unit_conversion',
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='recipes.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_unit',
            field=models.ForeignKey(default=1, help_text='Единица, в которую конвертируется', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='recipes.unit'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('ingredient', 'from_unit', 'to_unit'), name='unique_ingredient_unit_conversion'),
        ),
        migrations.RemoveField(
            model_name='unitconversion',
            name='base_unit',
        ),
        migrations.RemoveField(
            model_name='unitconversion',
            name='unit',
        ),
    ]
