# Generated by Django 6.0.3 on 2026-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_unitconversion_unique_ingredient_unit_conversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_piece',
            field=models.BooleanField(default=False, help_text='Считать ли товар в штуках (например, яйца, булочки)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='piece_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес одной штуки в базовых единицах (например, в граммах)', max_digits=8, null=True),
        ),
    ]
