# Generated by Django 6.0.3 on 2026-04-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_ingredient_is_piece_ingredient_piece_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-id'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Категория ингредиента', 'verbose_name_plural': 'Категории ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-id'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
    ]
