# Generated by Django 6.0.3 on 2026-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='per_serving_calories',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=8, verbose_name='Калории на порцию'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='per_serving_carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Углеводы на порцию'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='per_serving_fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Жиры на порцию'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='per_serving_proteins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Белки на порцию'),
        ),
    ]
