# Generated by Django 6.0.3 on 2026-05-13 07:59

import app.recipes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_populate_recipe_nutrition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['step_number'], 'verbose_name': 'Шаг приготовления рецепта', 'verbose_name_plural': 'Шаги приготовления рецептов'},
        ),
        migrations.AddField(
            model_name='recipestep',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=app.recipes.models._get_recipe_step_videopath, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.recipes.models._get_recipe_step_photopath, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='step_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер шага'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='timer',
            field=models.IntegerField(blank=True, help_text='Время таймера в минутах', null=True, verbose_name='Таймер (мин)'),
        ),
    ]
