# Generated by Django 6.0.3 on 2026-03-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('recipes', '0002_alter_ingredient_category_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.unit'),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
    ]
