# Generated by Django 6.0.3 on 2026-03-10 11:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_is_checked_alter_cartitem_unit_and_more'),
        ('recipes', '0004_alter_ingredient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'ingredient'], name='cart_item_user_id_7a97d7_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_checked'], name='cart_item_is_chec_71a2a4_idx'),
        ),
    ]
