# Generated by Django 6.0.3 on 2026-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзинах'},
        ),
    ]
