# Generated by Django 6.0.3 on 2026-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
