# Generated by Django 6.0.3 on 2026-04-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitem_is_checked'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_item_is_chec_71a2a4_idx',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_checked',
        ),
    ]
