# Generated by Django 6.0.3 on 2026-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='period',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('beakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_item',
        ),
    ]
