# Generated by Django 6.0.3 on 2026-03-10 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_period_alter_menuitem_meal_type_and_more'),
        ('recipes', '0004_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='day',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='day_offset',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu', 'day_offset'], name='menu_day_idx'),
        ),
    ]
