# Generated by Django 6.0.3 on 2026-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menuitem_day_menuitem_day_offset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='period',
            field=models.CharField(choices=[('day', 'День'), ('week', 'Неделя')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус'), ('drink', 'Напиток')], max_length=50),
        ),
    ]
