# Generated by Django 6.0.3 on 2026-03-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_audit_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.mealtype'),
        ),
    ]
