# Generated by Django 6.0.3 on 2026-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_mealtype_alter_menuitem_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
