# Generated by Django 6.0.3 on 2026-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_mealtype_alter_menuitem_meal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-created_at'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Позиция меню', 'verbose_name_plural': 'Позиции меню'},
        ),
    ]
