# Generated by Django 6.0.3 on 2026-03-26 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_menu_options_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='day_offset',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
