# Generated by Django 6.0.3 on 2026-03-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_alter_menuitem_day_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='day_offset',
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ]
            ),
        ),
    ]
