# Generated by Django 6.0.3 on 2026-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_alter_menuitem_day_offset_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='requested_cook_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
