# Generated by Django 6.0.3 on 2026-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_menuitem_requested_cook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='period',
            field=models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('custom', 'Свой план')], default='custom', max_length=20),
        ),
    ]
