# Generated by Django 6.0.3 on 2026-04-06 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_alter_menu_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
