# Generated by Django 6.0.3 on 2026-04-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_menuitem_servings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ['-id'], 'verbose_name': 'Прием пищи', 'verbose_name_plural': 'Приемы пищи'},
        ),
        migrations.AlterModelTable(
            name='mealtype',
            table='meal_type',
        ),
    ]
