# Generated by Django 6.0.3 on 2026-04-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_alter_mealtype_options_alter_mealtype_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Прием пищи', 'verbose_name_plural': 'Приемы пищи'},
        ),
    ]
