# Generated by Django 6.0.3 on 2026-04-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0014_alter_mealtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ['-id'], 'verbose_name': 'Прием пищи', 'verbose_name_plural': 'Приемы пищи'},
        ),
    ]
